tinyMCE.addI18n('en.advimage_dlg',{
tab_browser: "Browser",
upload_file_label: "Upload image",
upload_file_info: "file size limit 500kb(kilobytes) (.jpg, .gif, .png)",
upload_thumbnail_label: "don't generate thumbnail",
browser_close: "CLOSE",
browser_add_image: "Upload image",
remove_photo_submit: "Remove",
remove_photo_ask: "Do You want to remove image ?",
remove_folder_submit: "Remove",
remove_folder_ask: "Do You want to remove folder ?",
add_folder_label: "Add folder",
add_folder_info: "only signs (A-Z, a-z, 0-9)",
browser_add_folder: "Add folder",
add_folder_submit: "Add",
tab_appearance:"Appearance",
tab_advanced:"Advanced",
general:"General",
title:"Title",
preview:"Preview",
constrain_proportions:"Constrain proportions",
langdir:"Language direction",
langcode:"Language code",
long_desc:"Long description link",
style:"Style",
classes:"Classes",
ltr:"Left to right",
rtl:"Right to left",
id:"Id",
map:"Image map",
swap_image:"Swap image",
alt_image:"Alternative image",
mouseover:"for mouse over",
mouseout:"for mouse out",
misc:"Miscellaneous",
example_img:"Appearance preview image",
missing_alt:"Are you sure you want to continue without including an Image Description? Without it the image may not be accessible to some users with disabilities, or to those using a text browser, or browsing the Web with images turned off.",
dialog_title:"Insert/edit image",
src:"Image URL",
alt:"Image description",
list:"Image list",
border:"Border",
dimensions:"Dimensions",
width:"Width",
height:"Height",
vspace:"Vertical space",
hspace:"Horizontal space",
align:"Alignment",
align_baseline:"Baseline",
align_top:"Top",
align_middle:"Middle",
align_bottom:"Bottom",
align_texttop:"Text top",
align_textbottom:"Text bottom",
align_left:"Left",
align_right:"Right",
image_list:"Image list"
});